<a href="https://colab.research.google.com/github/mani2222278/Rebounce-Applied-AI-and-Analytics-code/blob/main/python_301.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MP-3 Clean ,Analyse $Summarise Real Dataset

# Import Pandas $ NumPy

In [3]:
import pandas as pd
import numpy as np

#Dataset Load

In [4]:
url = "https://huggingface.co/datasets/aarav912/online-retail/resolve/main/online_retail.csv"
df = pd.read_csv(url)

print("Dataset loaded successfully.")
print("Shape:", df.shape)
df.head()

Dataset loaded successfully.
Shape: (541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [5]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [6]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [7]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(5268)

In [9]:
df["Sales"] = df["Quantity"] * df["UnitPrice"]

print("Sales column created successfully.")
print(df[["Quantity", "UnitPrice", "Sales"]].head())

Sales column created successfully.
   Quantity  UnitPrice  Sales
0         6       2.55  15.30
1         6       3.39  20.34
2         8       2.75  22.00
3         6       3.39  20.34
4         6       3.39  20.34

In [10]:
median_sales = np.median(df["Sales"])

print("Median Sales:", median_sales)

Median Sales: 9.75

In [11]:
median_sales = np.median(df["Sales"].to_numpy())

print("Median Sales:", median_sales)

Median Sales: 9.75

#PART 2-CLEAN THE DATA

In [28]:
df = df.dropna(subset=["CustomerID"])

print("Shape after removing missing CustomerID:", df.shape)

Shape after removing missing CustomerID: (392692, 9)

Reason:
I removed rows with missing CustomerID becouse a valid customer number is needed for customer-level analysis

#convert InvoiceDate

In [13]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

print("Shape after converting InvoiceDate:", df.shape)
print("InvoiceDate data type:", df["InvoiceDate"].dtype)

Shape after converting InvoiceDate: (406829, 9)
InvoiceDate data type: datetime64[ns]

Remove duplicates

In [14]:
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (401604, 9)

Remove Invalid transaxtion

In [15]:
df = df[(df["Quantity"] > 0) & (df["UnitPrice"] > 0)]

print("Shape after removing invalid transactions:", df.shape)

Shape after removing invalid transactions: (392692, 9)

Sales column

In [16]:
df["Sales"] = df["Quantity"] * df["UnitPrice"]

print("Sales column created successfully.")
print(df[["Quantity", "UnitPrice", "Sales"]].head())

Sales column created successfully.
   Quantity  UnitPrice  Sales
0         6       2.55  15.30
1         6       3.39  20.34
2         8       2.75  22.00
3         6       3.39  20.34
4         6       3.39  20.34

 Part 3 - Numpy Analysis

In [17]:

mean_sales = np.mean(df["Sales"])
print("Mean Sales:", mean_sales)

median_sales = np.median(df["Sales"])
print("Median Sales:", median_sales)

min_sales = np.min(df["Sales"])
print("Minimum Sales:", min_sales)

max_sales = np.max(df["Sales"])
print("Maximum Sales:", max_sales)

std_sales = np.std(df["Sales"])
print("Standard Deviation:", std_sales)

Mean Sales: 22.6314997351614
Median Sales: 12.45
Minimum Sales: 0.001
Maximum Sales: 168469.6
Standard Deviation: 311.09882822360305

Explanation:
print("The mean and median are different, which shows that the sales values are not evenly distributed.")
print("If the mean is higher than the median, a small number of very large orders may be pulling the average upward.")

 Part 4 - Pandas Filtering

In [18]:

sales_above_500 = df[df["Sales"] > 500]

print("Number of transactions with Sales above 500:", len(sales_above_500))
print(sales_above_500)

Number of transactions with Sales above 500: 913
       InvoiceNo StockCode                     Description  Quantity  \
178       536387     79321                   CHILLI LIGHTS       192
179       536387     22780  LIGHT GARLAND BUTTERFILES PINK       192
180       536387     22779      WOODEN OWLS LIGHT GARLAND        192
181       536387     22466   FAIRY TALE COTTAGE NIGHTLIGHT       432
182       536387     21731   RED TOADSTOOL LED NIGHT LIGHT       432
...          ...       ...                             ...       ...
540069    581457     23401   RUSTIC MIRROR WITH LACE HEART       126
540070    581458     22197                  POPCORN HOLDER      1500
540071    581459     22197                  POPCORN HOLDER      1200
540421    581483     23843     PAPER CRAFT , LITTLE BIRDIE     80995
540425    581485     20749      ASSORTED COLOUR MINI CASES        84

               InvoiceDate  UnitPrice  CustomerID         Country      Sales
178    2010-12-01 09:58:00       3.82     16029.0  United Kingdom     733.44
179    2010-12-01 09:58:00       3.37     16029.0  United Kingdom     647.04
180    2010-12-01 09:58:00       3.37     16029.0  United Kingdom     647.04
181    2010-12-01 09:58:00       1.45     16029.0  United Kingdom     626.40
182    2010-12-01 09:58:00       1.25     16029.0  United Kingdom     540.00
...                    ...        ...         ...             ...        ...
540069 2011-12-08 18:43:00       4.15     18102.0  United Kingdom     522.90
540070 2011-12-08 18:45:00       0.72     17949.0  United Kingdom    1080.00
540071 2011-12-08 18:46:00       0.72     17949.0  United Kingdom     864.00
540421 2011-12-09 09:15:00       2.08     16446.0  United Kingdom  168469.60
540425 2011-12-09 09:38:00       6.35     17389.0  United Kingdom     533.40

[913 rows x 9 columns]

Largest transaction

In [19]:

largest_10 = df.sort_values("Sales", ascending=False).head(10)

print("10 Largest Transactions:")
print(largest_10)

10 Largest Transactions:
       InvoiceNo StockCode                          Description  Quantity  \
540421    581483     23843          PAPER CRAFT , LITTLE BIRDIE     80995
61619     541431     23166       MEDIUM CERAMIC TOP STORAGE JAR     74215
222680    556444     22502       PICNIC BASKET WICKER 60 PIECES        60
173382    551697      POST                              POSTAGE         1
348325    567423     23243  SET OF TEA COFFEE SUGAR TINS PANTRY      1412
160546    550461     21108   FAIRY CAKE FLANNEL ASSORTED COLOUR      3114
52711     540815     21108   FAIRY CAKE FLANNEL ASSORTED COLOUR      3114
421601    573003     23084                   RABBIT NIGHT LIGHT      2400
52709     540815    85123A   WHITE HANGING HEART T-LIGHT HOLDER      1930
160542    550461    85123A   WHITE HANGING HEART T-LIGHT HOLDER      1930

               InvoiceDate  UnitPrice  CustomerID         Country      Sales
540421 2011-12-09 09:15:00       2.08     16446.0  United Kingdom  168469.60
61619  2011-01-18 10:01:00       1.04     12346.0  United Kingdom   77183.60
222680 2011-06-10 15:28:00     649.50     15098.0  United Kingdom   38970.00
173382 2011-05-03 13:46:00    8142.75     16029.0  United Kingdom    8142.75
348325 2011-09-20 11:05:00       5.06     17450.0  United Kingdom    7144.72
160546 2011-04-18 13:20:00       2.10     15749.0  United Kingdom    6539.40
52711  2011-01-11 12:55:00       2.10     15749.0  United Kingdom    6539.40
421601 2011-10-27 12:11:00       2.08     14646.0     Netherlands    4992.00
52709  2011-01-11 12:55:00       2.55     15749.0  United Kingdom    4921.50
160542 2011-04-18 13:20:00       2.40     15749.0  United Kingdom    4632.00

Germany transaction

In [20]:
germany = df[df["Country"] == "Germany"]

print("Number of transactions from Germany:", len(germany))
print(germany)

Number of transactions from Germany: 9025
       InvoiceNo StockCode                          Description  Quantity  \
1109      536527     22809              SET OF 6 T-LIGHTS SANTA         6
1110      536527     84347  ROTATING SILVER ANGELS T-LIGHT HLDR         6
1111      536527     84945   MULTI COLOUR SILVER T-LIGHT HOLDER        12
1112      536527     22242        5 HOOK HANGER MAGIC TOADSTOOL        12
1113      536527     22244           3 HOOK HANGER MAGIC GARDEN        12
...          ...       ...                                  ...       ...
541801    581578     22993         SET OF 4 PANTRY JELLY MOULDS        12
541802    581578     22907     PACK OF 20 NAPKINS PANTRY DESIGN        12
541803    581578     22908        PACK OF 20 NAPKINS RED APPLES        12
541804    581578     23215     JINGLE BELL HEART ANTIQUE SILVER        12
541805    581578     22736          RIBBON REEL MAKING SNOWMEN         10

               InvoiceDate  UnitPrice  CustomerID  Country  Sales
1109   2010-12-01 13:04:00       2.95     12662.0  Germany  17.70
1110   2010-12-01 13:04:00       2.55     12662.0  Germany  15.30
1111   2010-12-01 13:04:00       0.85     12662.0  Germany  10.20
1112   2010-12-01 13:04:00       1.65     12662.0  Germany  19.80
1113   2010-12-01 13:04:00       1.95     12662.0  Germany  23.40
...                    ...        ...         ...      ...    ...
541801 2011-12-09 12:16:00       1.25     12713.0  Germany  15.00
541802 2011-12-09 12:16:00       0.85     12713.0  Germany  10.20
541803 2011-12-09 12:16:00       0.85     12713.0  Germany  10.20
541804 2011-12-09 12:16:00       2.08     12713.0  Germany  24.96
541805 2011-12-09 12:16:00       1.65     12713.0  Germany  16.50

[9025 rows x 9 columns]

Quantity above 1000

In [36]:
quantity_above_1000 = df[df["Quantity"] > 1000]

print("Transactions with Quantity above 1000:")
print(quantity_above_1000)

Transactions with Quantity above 1000:
       InvoiceNo StockCode                        Description  Quantity  \
4850      536809     84950     ASSORTED COLOUR T-LIGHT HOLDER      1824
4945      536830     84077  WORLD WAR 2 GLIDERS ASSTD DESIGNS      2880
4946      536830     21915             RED  HARMONICA IN BOX       1400
6365      536890    17084R              ASSORTED INCENSE PACK      1440
16435     537659     22189            CREAM HEART CARD HOLDER      1008
...          ...       ...                                ...       ...
533812    581115     22413    METAL SIGN TAKE IT OR LEAVE IT       1404
534952    581175     23084                 RABBIT NIGHT LIGHT      1440
540070    581458     22197                     POPCORN HOLDER      1500
540071    581459     22197                     POPCORN HOLDER      1200
540421    581483     23843        PAPER CRAFT , LITTLE BIRDIE     80995

               InvoiceDate  UnitPrice  CustomerID         Country      Sales
4850   2010-12-02 16:48:00       0.55     15299.0  United Kingdom    1003.20
4945   2010-12-02 17:38:00       0.18     16754.0  United Kingdom     518.40
4946   2010-12-02 17:38:00       1.06     16754.0  United Kingdom    1484.00
6365   2010-12-03 11:48:00       0.16     14156.0            EIRE     230.40
16435  2010-12-07 16:43:00       2.31     18102.0  United Kingdom    2328.48
...                    ...        ...         ...             ...        ...
533812 2011-12-07 12:20:00       2.75     15195.0  United Kingdom    3861.00
534952 2011-12-07 15:16:00       1.79     14646.0     Netherlands    2577.60
540070 2011-12-08 18:45:00       0.72     17949.0  United Kingdom    1080.00
540071 2011-12-08 18:46:00       0.72     17949.0  United Kingdom     864.00
540421 2011-12-09 09:15:00       2.08     16446.0  United Kingdom  168469.60

[104 rows x 9 columns]

 PART5 - GroupBy  and aggregation

In [22]:
summary = df.groupby("Country").agg(
    Number_of_Transactions=("Sales", "count"),
    Total_Sales=("Sales", "sum"),
    Average_Sales=("Sales", "mean")
).reset_index()

print("Country Summary:")
print(summary)

Country Summary:
                 Country  Number_of_Transactions  Total_Sales  Average_Sales
0              Australia                    1181   138453.810     117.234386
1                Austria                     398    10198.680      25.624824
2                Bahrain                      17      548.400      32.258824
3                Belgium                    2031    41196.340      20.283772
4                 Brazil                      32     1143.600      35.737500
5                 Canada                     151     3666.380      24.280662
6        Channel Islands                     747    20440.540      27.363507
7                 Cyprus                     603    13502.850      22.392786
8         Czech Republic                      25      826.740      33.069600
9                Denmark                     380    18955.340      49.882474
10                  EIRE                    7226   265262.460      36.709446
11    European Community                      60     1300.250      21.670833
12               Finland                     685    22546.080      32.913985
13                France                    8326   208934.310      25.094200
14               Germany                    9025   228678.400      25.338327
15                Greece                     145     4760.520      32.831172
16               Iceland                     182     4310.000      23.681319
17                Israel                     245     7215.840      29.452408
18                 Italy                     758    17483.240      23.064960
19                 Japan                     321    37416.370     116.561900
20               Lebanon                      45     1693.880      37.641778
21             Lithuania                      35     1661.060      47.458857
22                 Malta                     112     2725.590      24.335625
23           Netherlands                    2359   285446.340     121.003111
24                Norway                    1071    36165.440      33.767918
25                Poland                     330     7334.650      22.226212
26              Portugal                    1453    33375.840      22.970296
27                   RSA                      57     1002.310      17.584386
28          Saudi Arabia                       9      145.920      16.213333
29             Singapore                     222    21279.290      95.852658
30                 Spain                    2479    61558.560      24.832013
31                Sweden                     450    38367.830      85.261844
32           Switzerland                    1841    56443.950      30.659397
33                   USA                     179     3580.390      20.002179
34  United Arab Emirates                      68     1902.280      27.974706
35        United Kingdom                  349203  7285024.644      20.861862
36           Unspecified                     241     2660.770      11.040539

In [24]:
top_5_countries = summary.sort_values(
    "Total_Sales", ascending=False
).head(5)

print("Top 5 Countries by Total Sales:")
print(top_5_countries)

Top 5 Countries by Total Sales:
           Country  Number_of_Transactions  Total_Sales  Average_Sales
35  United Kingdom                  349203  7285024.644      20.861862
23     Netherlands                    2359   285446.340     121.003111
10            EIRE                    7226   265262.460      36.709446
14         Germany                    9025   228678.400      25.338327
13          France                    8326   208934.310      25.094200

In [25]:
highest_average = summary.sort_values(
    "Average_Sales", ascending=False
).head(1)

print("Country with Highest Average Sales:")
print(highest_average)

Country with Highest Average Sales:
        Country  Number_of_Transactions  Total_Sales  Average_Sales
23  Netherlands                    2359    285446.34     121.003111

In [26]:
top_country = summary.sort_values(
    "Total_Sales", ascending=False
).iloc[0]

print("Top-selling Country:", top_country["Country"])
print("Number of Transactions:", top_country["Number_of_Transactions"])
print("Total Sales:", top_country["Total_Sales"])

Top-selling Country: United Kingdom
Number of Transactions: 349203
Total Sales: 7285024.644

In [27]:
summary = summary.sort_values(
    "Total_Sales",
    ascending=False
)

print("Final Country Summary:")
print(summary)

Final Country Summary:
                 Country  Number_of_Transactions  Total_Sales  Average_Sales
35        United Kingdom                  349203  7285024.644      20.861862
23           Netherlands                    2359   285446.340     121.003111
10                  EIRE                    7226   265262.460      36.709446
14               Germany                    9025   228678.400      25.338327
13                France                    8326   208934.310      25.094200
0              Australia                    1181   138453.810     117.234386
30                 Spain                    2479    61558.560      24.832013
32           Switzerland                    1841    56443.950      30.659397
3                Belgium                    2031    41196.340      20.283772
31                Sweden                     450    38367.830      85.261844
19                 Japan                     321    37416.370     116.561900
24                Norway                    1071    36165.440      33.767918
26              Portugal                    1453    33375.840      22.970296
12               Finland                     685    22546.080      32.913985
29             Singapore                     222    21279.290      95.852658
6        Channel Islands                     747    20440.540      27.363507
9                Denmark                     380    18955.340      49.882474
18                 Italy                     758    17483.240      23.064960
7                 Cyprus                     603    13502.850      22.392786
1                Austria                     398    10198.680      25.624824
25                Poland                     330     7334.650      22.226212
17                Israel                     245     7215.840      29.452408
15                Greece                     145     4760.520      32.831172
16               Iceland                     182     4310.000      23.681319
5                 Canada                     151     3666.380      24.280662
33                   USA                     179     3580.390      20.002179
22                 Malta                     112     2725.590      24.335625
36           Unspecified                     241     2660.770      11.040539
34  United Arab Emirates                      68     1902.280      27.974706
20               Lebanon                      45     1693.880      37.641778
21             Lithuania                      35     1661.060      47.458857
11    European Community                      60     1300.250      21.670833
4                 Brazil                      32     1143.600      35.737500
27                   RSA                      57     1002.310      17.584386
8         Czech Republic                      25      826.740      33.069600
2                Bahrain                      17      548.400      32.258824
28          Saudi Arabia                       9      145.920      16.213333

 PART 6 -Merge and region analysis

In [29]:
region_lookup = {
    "United Kingdom": "Europe",
    "France": "Europe",
    "Germany": "Europe",
    "Spain": "Europe",
    "Netherlands": "Europe",
    "Belgium": "Europe",
    "Switzerland": "Europe",
    "Portugal": "Europe",
    "Australia": "Oceania",
    "Japan": "Asia",
    "USA": "Americas",
}

region_df = pd.DataFrame(list(region_lookup.items()), columns=["Country", "Region"])

# Left merge
merged = summary.merge(region_df, on="Country", how="left")
merged["Region"] = merged["Region"].fillna("Other")

print(merged.head(15))

# Total sales per region
region_summary = (
    merged.groupby("Region")["Total_Sales"]
          .sum()
          .sort_values(ascending=False)
)
print("\n--- Total Sales by Region ---")
print(region_summary)

           Country  Number_of_Transactions  Total_Sales  Average_Sales  \
0   United Kingdom                  349203  7285024.644      20.861862
1      Netherlands                    2359   285446.340     121.003111
2             EIRE                    7226   265262.460      36.709446
3          Germany                    9025   228678.400      25.338327
4           France                    8326   208934.310      25.094200
5        Australia                    1181   138453.810     117.234386
6            Spain                    2479    61558.560      24.832013
7      Switzerland                    1841    56443.950      30.659397
8          Belgium                    2031    41196.340      20.283772
9           Sweden                     450    38367.830      85.261844
10           Japan                     321    37416.370     116.561900
11          Norway                    1071    36165.440      33.767918
12        Portugal                    1453    33375.840      22.970296
13         Finland                     685    22546.080      32.913985
14       Singapore                     222    21279.290      95.852658

     Region
0    Europe
1    Europe
2     Other
3    Europe
4    Europe
5   Oceania
6    Europe
7    Europe
8    Europe
9     Other
10     Asia
11    Other
12   Europe
13    Other
14    Other

--- Total Sales by Region ---
Region
Europe      8200658.384
Other        507099.940
Oceania      138453.810
Asia          37416.370
Americas       3580.390
Name: Total_Sales, dtype: float64

In [31]:
summary_region = pd.merge(
    summary,
    region_df,
    on="Country",
    how="left"
)

summary_region["Region"] = summary_region["Region"].fillna("Other")

print("Country Summary with Region:")
print(summary_region)

Country Summary with Region:
                 Country  Number_of_Transactions  Total_Sales  Average_Sales  \
0         United Kingdom                  349203  7285024.644      20.861862
1            Netherlands                    2359   285446.340     121.003111
2                   EIRE                    7226   265262.460      36.709446
3                Germany                    9025   228678.400      25.338327
4                 France                    8326   208934.310      25.094200
5              Australia                    1181   138453.810     117.234386
6                  Spain                    2479    61558.560      24.832013
7            Switzerland                    1841    56443.950      30.659397
8                Belgium                    2031    41196.340      20.283772
9                 Sweden                     450    38367.830      85.261844
10                 Japan                     321    37416.370     116.561900
11                Norway                    1071    36165.440      33.767918
12              Portugal                    1453    33375.840      22.970296
13               Finland                     685    22546.080      32.913985
14             Singapore                     222    21279.290      95.852658
15       Channel Islands                     747    20440.540      27.363507
16               Denmark                     380    18955.340      49.882474
17                 Italy                     758    17483.240      23.064960
18                Cyprus                     603    13502.850      22.392786
19               Austria                     398    10198.680      25.624824
20                Poland                     330     7334.650      22.226212
21                Israel                     245     7215.840      29.452408
22                Greece                     145     4760.520      32.831172
23               Iceland                     182     4310.000      23.681319
24                Canada                     151     3666.380      24.280662
25                   USA                     179     3580.390      20.002179
26                 Malta                     112     2725.590      24.335625
27           Unspecified                     241     2660.770      11.040539
28  United Arab Emirates                      68     1902.280      27.974706
29               Lebanon                      45     1693.880      37.641778
30             Lithuania                      35     1661.060      47.458857
31    European Community                      60     1300.250      21.670833
32                Brazil                      32     1143.600      35.737500
33                   RSA                      57     1002.310      17.584386
34        Czech Republic                      25      826.740      33.069600
35               Bahrain                      17      548.400      32.258824
36          Saudi Arabia                       9      145.920      16.213333

      Region
0     Europe
1     Europe
2      Other
3     Europe
4     Europe
5    Oceania
6     Europe
7     Europe
8     Europe
9      Other
10      Asia
11     Other
12    Europe
13     Other
14     Other
15     Other
16     Other
17     Other
18     Other
19     Other
20     Other
21     Other
22     Other
23     Other
24     Other
25  Americas
26     Other
27     Other
28     Other
29     Other
30     Other
31     Other
32     Other
33     Other
34     Other
35     Other
36     Other

In [32]:
region_sales = summary_region.groupby("Region")["Total_Sales"].sum().reset_index()

region_sales = region_sales.sort_values(
    "Total_Sales",
    ascending=False
)

print("Total Sales by Region:")
print(region_sales)

Total Sales by Region:
     Region  Total_Sales
2    Europe  8200658.384
4     Other   507099.940
3   Oceania   138453.810
1      Asia    37416.370
0  Americas     3580.390

In [33]:
top_region = region_sales.iloc[0]

print("Region with Highest Total Sales:", top_region["Region"])
print("Total Sales:", top_region["Total_Sales"])

Region with Highest Total Sales: Europe
Total Sales: 8200658.384000001

PART 7 – ANSWER THE QUESTIONS

1. Which country generated the highest total sales?
ANSWAR - The United Kingdom generated the highest total sales, with approximately £7,285,024.64 in total sales.
2. Which country had the highest average transaction value?
ANSWAR - The Netherlands had the highest average transaction value, with an average of approximately £121.00 per transaction.
3. Which region performed best?
ANSWAR - The Europe region performed the best because it generated the highest total sales of approximately £8.20 million.
4. What is one interesting pattern you noticed in the data?
ANSWAR - An interesting pattern is that the United Kingdom dominates total sales and transaction count, while the Netherlands has a much higher average transaction value.
5. What is one data-quality problem you ran into, and how did you handle it?ANSWAR - The dataset contained missing CustomerID values and transactions with zero or negative Quantity/UnitPrice. I removed rows with missing CustomerID and filtered the data t

Part 8-final insight


# The cleaned Online Retail dataset shows that the United Kingdom dominates
# total sales, contributing more than £7.2 million. However, the average
# transaction value is highest in the Netherlands (£121), followed by
# Australia and Japan. This comparison reveals that while the UK generates
# volume, several smaller markets generate higher-value wholesale orders.
#
# The Sales distribution is right-skewed: the mean (£22.63) sits well above
# the median (£12.45), confirming that a small number of very large orders
# pull the average upward.
#
# One limitation is that we dropped all rows with missing CustomerID and
# all cancellation/refund rows. The final numbers therefore reflect only
# completed sales linked to known customers, and may understate the true
# scale of the business if many guest checkouts occurred