<a href="https://colab.research.google.com/github/mani2222278/Rebounce-Applied-AI-and-Analytics-code/blob/main/Q3_Pandas_and_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Session 4 Practice — Pandas & Combined Challenge
**Python for Data Analytics Bootcamp**

Solve each exercise in the code cell below it. Check your work against the matching Solutions notebook when done.

---

### Exercise 1 — A DataFrame from a dictionary

Import pandas using its standard alias, then build a DataFrame from the dictionary below and display it:

```python
{
    "product": ["Pen", "Notebook", "Eraser", "Marker"],
    "price": [10, 55, 8, 40],
    "in_stock": [120, 80, 200, 45],
}
```

In [1]:
# Write your code here
import pandas as pd

data = {
    "product": ["Pen", "Notebook", "Eraser", "Marker"],
    "price": [10, 55, 8, 40],
    "in_stock": [120, 80, 200, 45]
}

df = pd.DataFrame(data)

df

    product  price  in_stock
0       Pen     10       120
1  Notebook     55        80
2    Eraser      8       200
3    Marker     40        45

---

### Exercise 2 — Read a CSV file

Read the file `students.csv` (located in the same folder as this notebook) into a DataFrame named `students`, and display the first five rows.

In [9]:
from google.colab import files

uploaded = files.upload()

Saving students.csv to students.csv

In [10]:
# Write your code here
students = pd.read_csv("students.csv")

students.head()

           name  age       city  math_score  science_score  attendance
0   Aarav Mehta   19       Pune          78             85          92
1     Diya Nair   20      Kochi          91             88          96
2   Kabir Singh   18     Jaipur          65             72          80
3    Ananya Rao   21  Hyderabad          84             79          88
4  Vivaan Gupta   19      Delhi          73             68          75

---

### Exercise 3 — Shape and column names

Using the `students` DataFrame, print the number of rows and columns (its shape) and the list of column names.

In [11]:
# Write your code here
print(students.shape)
print(students.columns)

(10, 6)
Index(['name', 'age', 'city', 'math_score', 'science_score', 'attendance'], dtype='object')

---

### Exercise 4 — Summaries with info() and describe()

Display a concise technical summary of the `students` DataFrame using `info()`, and the summary statistics of its numeric columns using `describe()`.

In [12]:
# Write your code here
students.info()
print(students.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           10 non-null     object
 1   age            10 non-null     int64
 2   city           10 non-null     object
 3   math_score     10 non-null     int64
 4   science_score  10 non-null     int64
 5   attendance     10 non-null     int64
dtypes: int64(4), object(2)
memory usage: 612.0+ bytes
             age  math_score  science_score  attendance
count  10.000000   10.000000      10.000000   10.000000
mean   19.800000   78.500000      79.700000   85.800000
std     1.316561   11.673807      10.066998    8.954204
min    18.000000   59.000000      63.000000   70.000000
25%    19.000000   70.750000      73.250000   80.750000
50%    20.000000   80.000000      79.500000   87.000000
75%    20.750000   87.000000      87.250000   91.500000
max    22.000000   95.000000      94.000000   98.000000

---

### Exercise 5 — Select a single column

Select and display only the `math_score` column from the `students` DataFrame.

In [13]:
# Write your code here
students["math_score"]

0    78
1    91
2    65
3    84
4    73
5    88
6    59
7    95
8    70
9    82
Name: math_score, dtype: int64

---

### Exercise 6 — Select multiple columns

Select and display two columns together — `name` and `city` — from the `students` DataFrame.

In [14]:
# Write your code here
students[["name", "city"]]

           name       city
0   Aarav Mehta       Pune
1     Diya Nair      Kochi
2   Kabir Singh     Jaipur
3    Ananya Rao  Hyderabad
4  Vivaan Gupta      Delhi
5    Isha Verma    Lucknow
6     Rohan Das    Kolkata
7    Meera Iyer    Chennai
8   Arjun Reddy       Pune
9     Sara Khan     Mumbai

---

### Exercise 7 — Filter rows by a number

Display only the students whose `attendance` is greater than 90.

In [15]:
# Write your code here
students[students["attendance"] > 90]

          name  age     city  math_score  science_score  attendance
0  Aarav Mehta   19     Pune          78             85          92
1    Diya Nair   20    Kochi          91             88          96
7   Meera Iyer   18  Chennai          95             91          98

---

### Exercise 8 — Filter rows by text

Display only the students who live in `Pune`.

In [16]:
# Write your code here
students[students["city"] == "Pune"]

          name  age  city  math_score  science_score  attendance
0  Aarav Mehta   19  Pune          78             85          92
8  Arjun Reddy   21  Pune          70             77          83

---

### Exercise 9 — Average of a column

Calculate and print the average (mean) `math_score` of all students, rounded to one decimal place.

In [17]:
# Write your code here
print(round(students["math_score"].mean(), 1))

78.5

---

### Exercise 10 — Highest and lowest values

Print the highest and the lowest `science_score` in the `students` DataFrame.

In [18]:
# Write your code here
print("Highest:", students["science_score"].max())
print("Lowest:", students["science_score"].min())

Highest: 94
Lowest: 63

---

### Exercise 11 — Challenge — build objects and collect their data

Define an `Employee` class with attributes `name`, `department`, and `salary`. Create four Employee objects with different values, then collect their data into a list of dictionaries (one dictionary per employee).

In [19]:
# Write your code here
class Employee:
    def __init__(self, name, department, salary):
        self.name = name
        self.department = department
        self.salary = salary


emp1 = Employee("Rahul", "IT", 50000)
emp2 = Employee("Priya", "HR", 45000)
emp3 = Employee("Amit", "Finance", 55000)
emp4 = Employee("Neha", "Marketing", 48000)


employees = [
    {"name": emp1.name, "department": emp1.department, "salary": emp1.salary},
    {"name": emp2.name, "department": emp2.department, "salary": emp2.salary},
    {"name": emp3.name, "department": emp3.department, "salary": emp3.salary},
    {"name": emp4.name, "department": emp4.department, "salary": emp4.salary}
]

print(employees)

[{'name': 'Rahul', 'department': 'IT', 'salary': 50000}, {'name': 'Priya', 'department': 'HR', 'salary': 45000}, {'name': 'Amit', 'department': 'Finance', 'salary': 55000}, {'name': 'Neha', 'department': 'Marketing', 'salary': 48000}]

---

### Exercise 12 — Challenge — turn objects into a DataFrame

Convert the list of employee dictionaries from the previous exercise into a pandas DataFrame and display it. Then print the average salary across all four employees.

In [20]:
# Write your code here
employee_df = pd.DataFrame(employees)

print(employee_df)

print("Average salary:", employee_df["salary"].mean())

    name department  salary
0  Rahul         IT   50000
1  Priya         HR   45000
2   Amit    Finance   55000
3   Neha  Marketing   48000
Average salary: 49500.0